### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-intro-to-data-types#10]
Being very nitpicky here, so feel free to ignore whatever you want to ignore. 

In the Numbers section, you mention floats. Maybe a quick clarification on what that is vs. fixnums. 

It also casually mentions methods like Math.floor and Math.ceil. I think it's fine to keep this but maybe a quick note on the fact that they're methods which we'll cover laster. 

NaN seems pretty hard for a beginner, especially because we also talk about arguments and return values there

With strings, mentioning string interpolation might be too much right now. In Ruby, we have a simple lesson for it. 

I think assuming booleans are straightforward in JS might be too much of an assumption. Students may not know what a boolean even is (I didn't when I started Ruby). So explaining what they are instead of just having (true or false values in parentheses) can be helpful. 

With Undefined, saying that it's a "property of the global object" is a big phrase and can be confusing. Maybe some more clarification? I think Undefined and Null are pretty complicated for a second lesson mostly because they reference a lot of things like functions and objects that students don't know yet. 

For a larger alternative to this lesson, what do you think about introducing the idea of data types and listing all of them but really only focusing on numbers and strings and booleans? That way, string interpolation may also be covered since we're not bombarding them yet with too much info.

**Comment by pletcher** [comment]
- [ ] Break this up into one readme-lab pair per data type
- [ ] Get students to solve labs for each type

**Comment by jmburges** [comment]
👍

**Comment by pletcher** [comment]
We focused especially on strings and numbers, and moved some of the stuff on booleans into the flow control lessons.
