### ISSUE TITLE
This feels way too early in the curriculum

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-intro-to-data-types#20]
We don't talk about types until significantly later in the ruby curriculum. You discuss, variables, ECMAscript, functions, objects all kinds of stuff and they have written only one line of JS ever... `console.log("hello, world")`. 

How would students know what all of those things are and have enough knowledge to have felt the pain of not knowing about data types? Also there are so many new terms in this README that they'll be lost in those.

**Comment by pletcher** [comment]
I agree -- originally, most of this material came straight from the full-stack stuff, which came after students had worked through some Ruby. I've removed the quirky bits, and focused really hard on strings and numbers (with a tiny, tiny bit of booleans -- but we could even remove that).
