### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-intro-to-data-types#21]
First off, this lesson is sooooo much better. Super simplified and still presents good info. 

My only question is whether you should go a little bit more in depth with string interpolation instead of just linking to template literals. This is pretty much just adding a few lines explaining what the ${ } is and then how you did it in the lesson earlier, giving students some examples to practice with in the console. 

cc @jmburges

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/javascript-intro-to-data-types/commit/590e569513efa17a4b0990cdf7f02228ad0935e7
