### ISSUE TITLE
intro to js: why do we have a semi-colon here?

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/javascript-intro-to-data-types#23]
<img width="1004" alt="screen shot 2016-07-05 at 10 50 48 am" src="https://cloud.githubusercontent.com/assets/2243896/16588781/72214aa4-429e-11e6-972e-94db8e8e182b.png">

As a js newbie I thought it was required in order to return the string, but I don't think it is? I think we're using it as an ordinary semi-colon here, which is confusing to a newbie when each symbol on the screen matters. I think the // for commenting is enough of a separation. Let me know if I'm misunderstanding the purpose of the semi-colon.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
Yeah, that's true -- the semicolon is just a style thing -- we can remove them
