### ISSUE TITLE
"You should see 0.30000000000000004" example may be too much information

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co-curriculum/javascript-intro-to-data-types#25]
The example...
```
0.1 + 0.2
You should see 0.30000000000000004, which is plainly wrong. This is a common problem in programming: decimal points have to work a certain way because, deep down, they're represented in binary (as ones and zeroes). It's not important to know the details of how this behavior works right now (although we encourage you to search for resources online if you find it interesting!), but it is important to know that it happens.
```
...is interesting but as a beginner, this lesson/README is already very long and I'm not sure I understand the value of knowing this right now. Or even what it means for the future

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
